### ISSUE TITLE
feat: 大学物理实验

### ISSUE THREAD

**Issue by PA733** [longzheng268/Lanzhou_University_of_Technology_open_source_materials#2]
想 PR 个大物实验的分支。
请求建个空分支，然后我 PR 过来。

**Comment by longzheng268** [comment]
我有的，我目前都公开了，没公开的就是没的。




子非鱼安知鱼之乐&nbsp;&nbsp;&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "longzheng268/Lanzhou_University_of_Technology_open_source_materials"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月6日(星期四) 晚上10:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[longzheng268/Lanzhou_University_of_Technology_open_source_materials] feat: 大学物理实验 (Issue #2)





 
想 PR 个大物实验的分支。
 请求建个空分支，然后我 PR 过来。

**Comment by PA733** [comment]
OK，理解。

**Comment by longzheng268** [comment]
现在已经有大学物理实验分支了。
[大学物理实验分支](https://github.com/longzheng268/Lanzhou_University_of_Technology_open_source_materials/tree/%E5%A4%A7%E5%AD%A6%E7%89%A9%E7%90%86%E5%AE%9E%E9%AA%8C)
